CREATE SCHEMA [sit]
AUTHORIZATION [db_owner]
GO
GRANT ALTER ON SCHEMA:: [sit] TO [guest]
GO
GRANT CONTROL ON SCHEMA:: [sit] TO [guest]
GO
GRANT CREATE SEQUENCE ON SCHEMA:: [sit] TO [guest]
GO
GRANT DELETE ON SCHEMA:: [sit] TO [guest]
GO
GRANT EXECUTE ON SCHEMA:: [sit] TO [guest]
GO
GRANT INSERT ON SCHEMA:: [sit] TO [guest]
GO
GRANT REFERENCES ON SCHEMA:: [sit] TO [guest]
GO
GRANT SELECT ON SCHEMA:: [sit] TO [guest]
GO
GRANT TAKE OWNERSHIP ON SCHEMA:: [sit] TO [guest]
GO
GRANT UPDATE ON SCHEMA:: [sit] TO [guest]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [sit] TO [guest]
GO
GRANT VIEW CHANGE TRACKING ON SCHEMA:: [sit] TO [guest]
GO
