GRANT CREATE SEQUENCE ON SCHEMA:: [sys] TO [public] WITH GRANT OPTION
GO
GRANT DELETE ON SCHEMA:: [sys] TO [public] WITH GRANT OPTION
GO
GRANT EXECUTE ON SCHEMA:: [sys] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON SCHEMA:: [sys] TO [public] WITH GRANT OPTION
GO
GRANT REFERENCES ON SCHEMA:: [sys] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON SCHEMA:: [sys] TO [public] WITH GRANT OPTION
GO
